exports.addCall = require("./eventLoop/add");
exports.nextCall = require("./eventLoop/next");
exports.removeCall = require("./eventLoop/remove");
exports.addListener = require("./listener/add");
exports.getListeners = require("./listener/get");
exports.removeListener = require("./listener/remove");
exports.removeListeners = require("./listener/removeAll");
exports.addFunction = require("./slowFunction/add");
exports.addTimedFunction = require("./slowFunction/addTimed");
exports.getFunction = require("./slowFunction/get");
exports.addPromise = require("./promise/add");
exports.getPromise = require("./promise/get");
exports.rejectPromise = require("./promise/reject");
exports.resolvePromise = require("./promise/resolve");
//# sourceMappingURL=index.js.map