var immediate = require("./function/setImmediate");
var timeout = require("./function/setTimeout");
var interval = require("./function/setInterval");
var startSlowNode = require("./start");
var stopSlowNode = require("./exit");
exports.configuration = null;
exports.connection = null;
exports.start = startSlowNode;
exports.stop = stopSlowNode;
exports.setTimeout = timeout;
exports.setImmediate = immediate;
exports.setInterval = interval;
exports.EventEmitter = null;
exports.EventLoop = null;
exports.Promise = null;
//# sourceMappingURL=index.js.map