var immediate = require("./function/setImmediate");
var timeout = require("./function/setTimeout");
var interval = require("./function/setInterval");
var createDb = require("./store/db");
var startSlowNode = require("./start");
var stopSlowNode = require("./stop");
exports.configuration = null;
exports.connection = createDb();
exports.flushCallback = null;
exports.start = startSlowNode;
exports.stop = stopSlowNode;
exports.flush = null;
exports.setTimeout = timeout;
exports.setImmediate = immediate;
exports.setInterval = interval;
exports.Promise = null;
exports.Event = null;
//# sourceMappingURL=index.js.map