var store = require("../store/eventLoop");
var processEvent = require("./calls/run");
var flushCall = require("./calls/flush");
exports.add = store.add;
exports.run = processEvent;
exports.remove = store.remove;
exports.getNext = store.getNext;
exports.flush = flushCall;
//# sourceMappingURL=api.js.map