var store = require("../store/index");
var execCall = require("./exec");
var runLoop = require("./runLoop");
exports.add = store.addCall;
exports.exec = execCall;
exports.remove = store.removeCall;
exports.getNext = store.nextCall;
exports.flush = runLoop;
//# sourceMappingURL=index.js.map